-- =============================================================
-- Petopia DB -- 003: core (D1 spec sec 2 "Isolation", 3.2, 3.4, 3.7, 7.1; A3, A7).
-- One workspace = the household. Every content table is FORCE RLS with the fail-closed policy (Vitalis 003):
-- an unset app.current_workspace_id matches nothing. The one gate table, core.access_grant, carries no RLS on
-- purpose: it is read before a workspace is chosen (Vitalis 003 / Truehaven 008). Deny by default: no grant row,
-- or a revoked one, means no access. Idempotent.
-- =============================================================

CREATE TABLE IF NOT EXISTS core.workspace (
  workspace_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind         text NOT NULL DEFAULT 'HOUSEHOLD' CHECK (kind IN ('HOUSEHOLD')),
  display_name text NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  created_by   text NOT NULL
);

CREATE TABLE IF NOT EXISTS core.member (
  member_id    bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  workspace_id bigint NOT NULL REFERENCES core.workspace(workspace_id),
  member_name  text NOT NULL CHECK (length(trim(member_name)) > 0),   -- the Synapse identity
  display_name text NULL,
  is_child     boolean NOT NULL DEFAULT false,
  created_at   timestamptz NOT NULL DEFAULT now(),
  created_by   text NOT NULL,
  UNIQUE (workspace_id, member_name)
);

CREATE TABLE IF NOT EXISTS core.contact (
  contact_id   bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  workspace_id bigint NOT NULL REFERENCES core.workspace(workspace_id),
  kind         text NOT NULL CHECK (kind IN ('VET_PRACTICE','VET_PERSON','EMERGENCY_VET','BREEDER','RESCUE','INSURER','GROOMER','KENNEL','PERSON','WILDLIFE_RESCUE')),
  name         text NOT NULL CHECK (length(trim(name)) > 0),
  phone        text NULL,
  email        text NULL,
  address      text NULL,
  retired_at   timestamptz NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  created_by   text NOT NULL,
  CONSTRAINT contact_ws_id UNIQUE (workspace_id, contact_id)
);

-- Habitat is first-class from day one (sec 3.4, R sec 25): Home, Garden seeded below.
CREATE TABLE IF NOT EXISTS core.habitat (
  habitat_id   bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  workspace_id bigint NOT NULL REFERENCES core.workspace(workspace_id),
  name         text NOT NULL CHECK (length(trim(name)) > 0),
  kind         text NOT NULL CHECK (kind IN ('HOME','GARDEN','POND','AQUARIUM','FEEDER','NEST_BOX','TERRARIUM','STABLE','OTHER')),
  parent_id    bigint NULL,
  ext          jsonb NOT NULL DEFAULT '{}'::jsonb,
  retired_at   timestamptz NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  created_by   text NOT NULL,
  CONSTRAINT habitat_ws_id UNIQUE (workspace_id, habitat_id),
  CONSTRAINT habitat_ws_name UNIQUE (workspace_id, name),
  CONSTRAINT habitat_parent_fk FOREIGN KEY (workspace_id, parent_id) REFERENCES core.habitat(workspace_id, habitat_id),
  CONSTRAINT habitat_not_own_parent CHECK (parent_id IS NULL OR parent_id <> habitat_id)
);

-- RLS on every content table. core.workspace is included: a session sees only its own household row.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['workspace','member','contact','habitat'] LOOP
    EXECUTE format('ALTER TABLE core.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE core.%I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('DROP POLICY IF EXISTS workspace_isolation ON core.%I', t);
    EXECUTE format($p$CREATE POLICY workspace_isolation ON core.%I USING (workspace_id = NULLIF(current_setting('app.current_workspace_id', true), '')::bigint)$p$, t);
  END LOOP;
END $$;

-- The household gate (sec 7.1 layer 1). Deny by default. No RLS -- see header.
CREATE TABLE IF NOT EXISTS core.access_grant (
  access_grant_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  workspace_id    bigint NOT NULL REFERENCES core.workspace(workspace_id),
  member_name     text NOT NULL CHECK (length(trim(member_name)) > 0),
  granted_by      text NOT NULL,
  granted_at      timestamptz NOT NULL DEFAULT now(),
  revoked_by      text NULL,
  revoked_at      timestamptz NULL,
  CONSTRAINT access_grant_revoked_pair CHECK ((revoked_at IS NULL) = (revoked_by IS NULL)),
  UNIQUE (workspace_id, member_name)
);
CREATE INDEX IF NOT EXISTS idx_access_grant_member ON core.access_grant(member_name) WHERE revoked_at IS NULL;

-- The household itself (workspace 1) and its two seeded habitats. The settings are session-local to this
-- migration's psql run, so the inserts pass the FORCE RLS policy. Re-running changes nothing.
SELECT set_config('app.current_workspace_id', '1', false);
INSERT INTO core.workspace (workspace_id, kind, display_name, created_by)
  VALUES (1, 'HOUSEHOLD', 'Household', 'migration-003') ON CONFLICT (workspace_id) DO NOTHING;
-- The identity sequence must never hand out 1 again; only move it forward, never back.
DO $$
DECLARE seq text := pg_get_serial_sequence('core.workspace', 'workspace_id'); called boolean;
BEGIN
  EXECUTE format('SELECT is_called FROM %s', seq) INTO called;
  IF NOT called THEN PERFORM setval(seq, 1, true); END IF;
END $$;
INSERT INTO core.habitat (workspace_id, name, kind, created_by) VALUES
  (1, 'Home', 'HOME', 'migration-003'),
  (1, 'Garden', 'GARDEN', 'migration-003')
  ON CONFLICT (workspace_id, name) DO NOTHING;
UPDATE core.habitat g SET parent_id = h.habitat_id
  FROM core.habitat h
 WHERE g.workspace_id = 1 AND h.workspace_id = 1 AND g.name = 'Garden' AND h.name = 'Home' AND g.parent_id IS NULL;
SELECT set_config('app.current_workspace_id', '', false);
