// Same setup as Vitalis (spec sec 2): one pool on PETOPIA_DATABASE_URL, every read or write inside a transaction that
// has chosen exactly one workspace -- or none, in which case FORCE RLS shows nothing (fail-closed). Kysely is the
// typed query builder over the same transaction's client (Epicure db.ts); raw SQL is still fine where clearer.
import { Kysely, PostgresDialect, type ColumnType, type Generated } from 'kysely';
import pg from 'pg';

export type Client = pg.PoolClient;

// `date` columns come back as 'YYYY-MM-DD' text, never a JS Date at local midnight (which can shift the day).
pg.types.setTypeParser(1082, (v: string) => v);

let pool: pg.Pool | null = null;

export function getPool(): pg.Pool {
  if (!pool) {
    const connectionString = process.env.PETOPIA_DATABASE_URL;
    if (!connectionString) throw new Error('PETOPIA_DATABASE_URL is not set');
    pool = new pg.Pool({ connectionString, max: 10 });
  }
  return pool;
}

export async function closePool(): Promise<void> {
  if (pool) {
    const p = pool;
    pool = null;
    await p.end();
  }
}

/** Runs fn in one transaction. workspaceId null = no household chosen: every content table reads as empty. */
export async function withTxn<T>(workspaceId: number | null, readOnly: boolean, fn: (c: Client) => Promise<T>): Promise<T> {
  const c = await getPool().connect();
  let failed = false;
  try {
    await c.query(readOnly ? 'BEGIN READ ONLY' : 'BEGIN');
    // Always set it, even when empty: a pooled connection can carry an old value otherwise (Vitalis / Truehaven 007).
    await c.query("SELECT set_config('app.current_workspace_id', $1, true)", [workspaceId ? String(workspaceId) : '']);
    const out = await fn(c);
    await c.query('COMMIT');
    return out;
  } catch (e) {
    failed = true;
    await c.query('ROLLBACK').catch(() => undefined);
    throw e;
  } finally {
    c.release(failed); // a connection whose transaction failed is closed, not reused: nothing half-done can leak into the next one
  }
}

// ---- Kysely types, table by table as slices land (Epicure's rule). pg returns bigint as a string, so bigint columns
// select as string and insert as number; timestamptz selects as Date.
type BigId = ColumnType<string, number, number>;
type BigIdNull = ColumnType<string | null, number | null | undefined, number | null>;
type Serial = ColumnType<string, never, never>; // generated by Postgres, never written
type Created = ColumnType<Date, never, never>;

export interface AnimalTable {
  animal_id: Serial;
  workspace_id: BigId;
  name: string;
  nickname: string | null;
  species_id: BigId;
  breed: string | null;
  module_code: string;
  ext: ColumnType<Record<string, unknown>, string, string>;
  ext_schema_version: number;
  sex: Generated<string>;
  neuter_status: Generated<string>;
  colour_markings: string | null;
  born_on: string | null;
  born_precision: Generated<string>;
  acquired_on: string | null;
  acquired_precision: Generated<string>;
  source: string | null;
  microchip: string | null;
  registration: string | null;
  vet_contact_id: BigIdNull;
  emergency_contact_id: BigIdNull;
  habitat_id: BigIdNull;
  profile_media_id: BigIdNull;
  status: Generated<string>;
  status_on: string | null;
  kind: Generated<string>;
  health_status: string | null;
  health_status_by: string | null;
  health_status_at: ColumnType<Date | null, string | null | undefined, string | null>;
  created_at: Created;
  created_by: string;
  updated_at: ColumnType<Date, never, string>;
}
export interface SpeciesTable { species_id: Serial; common_name: string; scientific_name: string | null; group: string; domain: string; sensitive: boolean }
export interface SpeciesModuleTable { code: string; species_id: string | null; schema: Record<string, unknown>; schema_version: number; measures: string[]; default_routines: unknown; vaccine_set: string[] }
export interface MediaItemTable { media_item_id: Serial; workspace_id: BigId; sha256: string; path: string; width: number; height: number; taken_on: string | null; added_by: string; retired_at: ColumnType<Date | null, never, null>; created_at: Created }
export interface HabitatTable { habitat_id: Serial; workspace_id: BigId; name: string; kind: string; parent_id: BigIdNull; ext: unknown; retired_at: Date | null; created_at: Created; created_by: string }
export interface AnimalRoleTable { animal_role_id: Serial; workspace_id: BigId; animal_id: BigId; member_name: string; role: string; from_on: Generated<string>; to_on: string | null; set_by: string; set_at: Created }

export interface DB {
  'animal.animal': AnimalTable;
  'ref.species': SpeciesTable;
  'ref.species_module': SpeciesModuleTable;
  'media.item': MediaItemTable;
  'core.habitat': HabitatTable;
  'core.animal_role': AnimalRoleTable;
}

/** A Kysely bound to this transaction's client: queries run inside the same BEGIN ... COMMIT and the same RLS setting. */
export function kdb(c: Client): Kysely<DB> {
  const single = {
    connect: () => Promise.resolve({ query: c.query.bind(c), release: () => undefined }),
    end: () => Promise.resolve(),
  };
  return new Kysely<DB>({ dialect: new PostgresDialect({ pool: single }) });
}

/** pg returns bigint and numeric as strings; these keep the conversions in one place. */
export const toId = (v: unknown): number => Number(v);
